### PR TITLE
minor CI fixes

### PR DESCRIPTION
**Pull request by MuellerSeb**
- rewrite triggers
  - only master and develop are running
  - only PRs to develop (all origins)
- workflow_dispatch fix
- pin version of cibuildwheel
- test.pypi for develop and master

### CODE REVIEW

**Review by LSchueler — COMMENTED** [review]
Fixing CIBW version is fine, testing the deployment of the master branch too, but the conditions at the beginning will again cause internal PRs to be built and tested twice.

**Comment by MuellerSeb** [comment]
> ... the conditions at the beginning will again cause internal PRs to be built and tested twice.

Actually this shouldn't happen.
1. When pushed to a branch:
  - "master"/"develop" -> triggered
  - every other branch -> not triggered
2. PRs should only be against "master"/"develop" (at least that is what we do up to now)
  - only trigger if base branch is "develop"
  - when base branch is "master", PR should come from "develop"
    - then PR is not triggering
    - develop is triggered as a branch
  - when branch is other than "master"/"develop" nothing is triggered until a PR is opened against "develop"

**Comment by LSchueler** [comment]
I'm not exactly sure how the event `pull_request` is defined. Are you sure that every push to a branch which has an open PR triggers `pull_request`? - Otherwise, with your suggestion, the CI would only run once, when the PR is opened from a forked repo.

**Comment by MuellerSeb** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request

> **Note**: By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.

and "synchronize" refers to any update in the source branch ([link](https://github.community/t/what-is-a-pull-request-synchronize-event/14784))

So I think it should work. Maybe just try?

**Comment by LSchueler** [comment]
That's really missing in the Actions doc, right? - Yeah, let's just try it.

**Review by LSchueler — APPROVED** [review]

**Comment by MuellerSeb** [comment]
> That's really missing in the Actions doc, right? - Yeah, let's just try it.

Yeah.. the docs are really missing some important informations.. guess it's still work in progress. But hey, they are building a hell of a machine there!

**Pull request merged**
