### PR TITLE
Add more contact channls to READMEs

### PR DESCRIPTION
**Pull request by LSchueler**
I think we should also add our email address to the "get in touch" section. I've also added these badges to the readthedocs readme. I think I remember that we once had them already there. Am I mistaken or is there a reason why we do not have them for readthedocs? - I think the "get in touch" there is at least as important as it is on the github page.

Do you think we should add a fancy email logo?

And then we still have the "Contact" section at the end of the readme. But I think this is OK if we only keep the email address there. Opinions?

### CODE REVIEW

**Comment by MuellerSeb** [comment]
What about this for the email badge?
```
https://img.shields.io/badge/Email-GeoStat--Framework-468a88?style=flat&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIj48cGF0aCBkPSJNNDQ4IDg4SDUyYy0yNyAwLTQ5IDIyLTQ5IDQ5djIyNmMwIDI3IDIyIDQ5IDQ5IDQ5aDM5NmMyNyAwIDQ5LTIyIDQ5LTQ5VjEzN2MwLTI3LTIyLTQ5LTQ5LTQ5em0xNiA0OXYyMjZsLTIgNy0xMTUtMTE2IDExNy0xMTd6TTM2IDM2M1YxMzdsMTE3IDExN0wzOCAzNzBsLTItN3ptMjE5LTYzYy0zIDMtNyAzLTEwIDBMNjYgMTIxaDM2OHptLTc5LTIzIDQ2IDQ2YTM5IDM5IDAgMCAwIDU2IDBsNDYtNDYgMTAxIDEwMkg3NXoiIHN0eWxlPSJmaWxsOiNmNWY1ZjU7ZmlsbC1vcGFjaXR5OjEiLz48L3N2Zz4=
```
Email

I also just found out, that I didn't use the correct colors for the Gitter badges (see: https://simpleicons.org/):
- Gitter: `ED1965` (could you change that here as well?)

And there is already a badge for the swung slack channel (See: https://github.com/softwareunderground/badges):
```
https://img.shields.io/badge/Swung-Slack-4A154B?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABmJLR0QA%2FwD%2FAP%2BgvaeTAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH5AYaFSENGSa5qgAABmZJREFUSMeFlltsVNcVhr%2B1z5m7Zzy%2BxaBwcQrGQOpgCAkKtSBQIqJepKhPBULpQ6sKBVWVKqXtSy%2BR0qYXqa2qRmlDCzjBEZGKUCK1TWqlNiGIEKDQBtf4Fki4OIxnxrex53LOXn2YwbjEtOvlHG3tvX%2Btf%2B21%2Fl%2BYJ1QVEbn1vwLYBWwCVgG1lW0ZoA%2FoAQ6LSP%2BdZ%2BeGzAMiIqK%2Bem0GpxNYVeBj3j2b4NCfM2QnfAAaa11al4fZuCZK24owQJ9v%2BbLryIVbd9wVSNUaEWNVtQPYfXHmAD0T32ZJeBM1Q8d0zzMDUpMwAFgLJU%2BxClURw9NfqedLWxMAHSKyR1WNiNhPAM0B6c%2FbdPORTLuOeUMSNkmMBHgyeo32bwwRDMh8bDM%2BZVl0j6uvPrdYknFnSESWzwUzt%2BkyVlUHx7zh5j%2BmPkXBjosjLkWdominiMQ%2BoiEZxuq8OFRXGXJ5K5%2Fde5nha8VlqjooIlZVBcBUiqeqemjGppd1ptfhSpS8pmmN7GVf4whPNY4Di9m%2BMcR03nK3sBbCQeFbv7gBsExVOyp3l6nz1VtjcM4fTK3Uok5IXtPsrHuPevcBXk8d4dWPX6I%2BsIB9wf1s%2B2Y%2FVbFynUIBIeDeplIECiXl5Iv3kbLogogRgbWukfNumT%2FnlYszBxj3hwXg0cQvqXcfYNu5tVyYPE%2B1G8dXn%2BfW72fH49U8sSlOPGr4SccoF4cKs3WzFrY%2BFCMUNmz%2Ba0aeWR1l15JwJ7DaVPpk1YnJ7xIxtQRNjDXRvTx%2F9ef0Tl0g6SYQhAlvmkH%2Fgv74qUaiTSG8ewJ0%2FGgRK5aG8Cts5ouWDa1RxoDRovK9i9MAq1S12QA7b5ROUdBxBIeQ1ACG49m%2FEXPis7Qk3ChHbx6Qw1dgXVeWB7uyDOctP%2Fx6w2zdrIVIyFCyiq8wXlJOZzyAXQbY%2FGGhC8EAilJ%2BVg7ufxU6IAHeSvewfQEadiDuCr%2B6NE1LU4hwUFAF1xFGRkvEjVDlgiPwVqoEsNkAq0ZKp3EIYrFM2xGm7Uc8u%2FzXjHkTmHIHoCiDM73E3IIsDCtRV3gn7QHQ0hTCt0ooKLw%2FWCAM1AcNISOcHSsBrDRAbc7eQMQBFFciHM18kaZIMz3r%2F0HO5mazytsiw%2FmTtCYiGGCkQlltwkEVjMDVmyUA6oIGR%2BDGjAWoM3f2giHAhH%2BFI5nPsDrWxqWNE9S4tUz5k1S7cQ5df4k9S6qY9JRipXtr4w5WQYH0eHkWrqxy8FTn3AvpmFmIqj%2B76EiQjNfHH1JNWFKc3vABj9V9npw%2FRXfmBNsaoTRnRAQDAgqqMJr1KBWUtUmHaR8WRgzAqAH6FgYexqd4R2Yuns5wcLSFK4U36bj%2FdbbUbGdoZoCi3uS%2Bqtt73TlNWygpqXGfZTGXnKesrwkA9BmgZ0noMZT5R0tQ4hzLfo4rhS46W%2F%2BCAn3T7%2BhDySiWMl2RkHArP8dAesKjPixYVbbUBwB6DHB4QWADIamuHPtkhE0t3ZP7ANhe9zgvXP2dfK0pymRJmQLiEYNW6mEVljYGuDzlkwwaHq51AQ4bERkAetvjP2XCT6H480AJeZsB4N7QYt7OnuSROtRXJV2wNNS4qIJvlbUtERJxhxcv5%2FlNWwygV0QGyzKBv%2FP%2ByFfZXf%2ButoR3UuXcS95mKNgxSjpN3qZZFHwUgFPjx5n2c9wo9ktrtcOZtMeWB2NEw4b2thivPLuIS1M%2BAzmrTy4O4ys7Zv1B5fsnVdWCr7PxYf7vej73ex2YeU1VVY9nu7ShG63vRo%2Fe%2FK1%2B518FbXkjo3OjO1XU2LFRzRZ9VdWDczFQ1VsCOHgpd1G%2FcG6jHrj2vPbn%2BjVdHNfr%2BRH92eXva2MPuvxEQpe%2BHdEnzm%2FQf4%2BrRo%2BldMUbGd393oS2dWU0cDSlw1OequrALVG9Q8rLsquqg2OlzLL2Myu1N5eShgB4CjEnSMSJYrX8Oj0t8UH7NMnX0iSDwmhBWRl3tKs9IcmgGRSRZqtqzFwpL4uWWKvWiMjyZKC24%2F1HbsrLn95Pwk3gCpS0yIw%2Fg6clPC2RLc3QmzvJupoARQsvrItxZmtSkkFz6E6Q%2F2m3PFta44jbCaw%2BO3GK7uybnJs8xfXC1fLYCdTz9NIfsCS0mYVhAHp9ZYdr5J%2F%2F127dxUA2AzuBzRUDWVfZlq4YyG6gs9ImdzWQ%2FwFNRlgCFdG5bAAAAABJRU5ErkJggg%3D%3D
```
![swung-slack-gstools](https://img.shields.io/badge/Swung-Slack-4A154B?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABmJLR0QA%2FwD%2FAP%2BgvaeTAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH5AYaFSENGSa5qgAABmZJREFUSMeFlltsVNcVhr%2B1z5m7Zzy%2BxaBwcQrGQOpgCAkKtSBQIqJepKhPBULpQ6sKBVWVKqXtSy%2BR0qYXqa2qRmlDCzjBEZGKUCK1TWqlNiGIEKDQBtf4Fki4OIxnxrex53LOXn2YwbjEtOvlHG3tvX%2Btf%2B21%2Fl%2BYJ1QVEbn1vwLYBWwCVgG1lW0ZoA%2FoAQ6LSP%2BdZ%2BeGzAMiIqK%2Bem0GpxNYVeBj3j2b4NCfM2QnfAAaa11al4fZuCZK24owQJ9v%2BbLryIVbd9wVSNUaEWNVtQPYfXHmAD0T32ZJeBM1Q8d0zzMDUpMwAFgLJU%2BxClURw9NfqedLWxMAHSKyR1WNiNhPAM0B6c%2FbdPORTLuOeUMSNkmMBHgyeo32bwwRDMh8bDM%2BZVl0j6uvPrdYknFnSESWzwUzt%2BkyVlUHx7zh5j%2BmPkXBjosjLkWdominiMQ%2BoiEZxuq8OFRXGXJ5K5%2Fde5nha8VlqjooIlZVBcBUiqeqemjGppd1ptfhSpS8pmmN7GVf4whPNY4Di9m%2BMcR03nK3sBbCQeFbv7gBsExVOyp3l6nz1VtjcM4fTK3Uok5IXtPsrHuPevcBXk8d4dWPX6I%2BsIB9wf1s%2B2Y%2FVbFynUIBIeDeplIECiXl5Iv3kbLogogRgbWukfNumT%2FnlYszBxj3hwXg0cQvqXcfYNu5tVyYPE%2B1G8dXn%2BfW72fH49U8sSlOPGr4SccoF4cKs3WzFrY%2BFCMUNmz%2Ba0aeWR1l15JwJ7DaVPpk1YnJ7xIxtQRNjDXRvTx%2F9ef0Tl0g6SYQhAlvmkH%2Fgv74qUaiTSG8ewJ0%2FGgRK5aG8Cts5ouWDa1RxoDRovK9i9MAq1S12QA7b5ROUdBxBIeQ1ACG49m%2FEXPis7Qk3ChHbx6Qw1dgXVeWB7uyDOctP%2Fx6w2zdrIVIyFCyiq8wXlJOZzyAXQbY%2FGGhC8EAilJ%2BVg7ufxU6IAHeSvewfQEadiDuCr%2B6NE1LU4hwUFAF1xFGRkvEjVDlgiPwVqoEsNkAq0ZKp3EIYrFM2xGm7Uc8u%2FzXjHkTmHIHoCiDM73E3IIsDCtRV3gn7QHQ0hTCt0ooKLw%2FWCAM1AcNISOcHSsBrDRAbc7eQMQBFFciHM18kaZIMz3r%2F0HO5mazytsiw%2FmTtCYiGGCkQlltwkEVjMDVmyUA6oIGR%2BDGjAWoM3f2giHAhH%2BFI5nPsDrWxqWNE9S4tUz5k1S7cQ5df4k9S6qY9JRipXtr4w5WQYH0eHkWrqxy8FTn3AvpmFmIqj%2B76EiQjNfHH1JNWFKc3vABj9V9npw%2FRXfmBNsaoTRnRAQDAgqqMJr1KBWUtUmHaR8WRgzAqAH6FgYexqd4R2Yuns5wcLSFK4U36bj%2FdbbUbGdoZoCi3uS%2Bqtt73TlNWygpqXGfZTGXnKesrwkA9BmgZ0noMZT5R0tQ4hzLfo4rhS46W%2F%2BCAn3T7%2BhDySiWMl2RkHArP8dAesKjPixYVbbUBwB6DHB4QWADIamuHPtkhE0t3ZP7ANhe9zgvXP2dfK0pymRJmQLiEYNW6mEVljYGuDzlkwwaHq51AQ4bERkAetvjP2XCT6H480AJeZsB4N7QYt7OnuSROtRXJV2wNNS4qIJvlbUtERJxhxcv5%2FlNWwygV0QGyzKBv%2FP%2ByFfZXf%2ButoR3UuXcS95mKNgxSjpN3qZZFHwUgFPjx5n2c9wo9ktrtcOZtMeWB2NEw4b2thivPLuIS1M%2BAzmrTy4O4ys7Zv1B5fsnVdWCr7PxYf7vej73ex2YeU1VVY9nu7ShG63vRo%2Fe%2FK1%2B518FbXkjo3OjO1XU2LFRzRZ9VdWDczFQ1VsCOHgpd1G%2FcG6jHrj2vPbn%2BjVdHNfr%2BRH92eXva2MPuvxEQpe%2BHdEnzm%2FQf4%2BrRo%2BldMUbGd393oS2dWU0cDSlw1OequrALVG9Q8rLsquqg2OlzLL2Myu1N5eShgB4CjEnSMSJYrX8Oj0t8UH7NMnX0iSDwmhBWRl3tKs9IcmgGRSRZqtqzFwpL4uWWKvWiMjyZKC24%2F1HbsrLn95Pwk3gCpS0yIw%2Fg6clPC2RLc3QmzvJupoARQsvrItxZmtSkkFz6E6Q%2F2m3PFta44jbCaw%2BO3GK7uybnJs8xfXC1fLYCdTz9NIfsCS0mYVhAHp9ZYdr5J%2F%2F127dxUA2AzuBzRUDWVfZlq4YyG6gs9ImdzWQ%2FwFNRlgCFdG5bAAAAABJRU5ErkJggg%3D%3D)

Or we keep the current badge (I also like the slack logo)

**Review by MuellerSeb — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by MuellerSeb** [comment]
And could you move the "Get in touch" section directly under the logo as well in rtd?

**Comment by LSchueler** [comment]
Good ideas, thanks!

I've
- moved the badges directly beneath the GSTools logo
- used the email logo
- updated the gitter colour (although I really cannot see any difference :-) )
- updated the slack logo.

I've also found a typo ;-)

**Comment by MuellerSeb** [comment]
I just created a new badge for swung: https://github.com/softwareunderground/badges/pull/2
and I found out, that there is a simpler URL to the gstools channel there:
```
[![swung-slack-gstools](https://img.shields.io/badge/Swung-Slack-4A154B?style=flat&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MDAiIGhlaWdodD0iODAwIj48cGF0aCB0cmFuc2Zvcm09Im1hdHJpeCgxLjEwMjcgMCAwIDEuMTAzMzggLTQxIC00MikiIGQ9Ik0zMDkgNjdhMzQ2IDM0NiAwIDAgMC0yMDAgNTE4YzY1IDIxIDEzMyA0NyAyMDIgMzcgNTYtMTYgNjYtOTUgMjktMTM0LTQzLTUzLTExNS03OC0xNDQtMTQyLTIzLTYzIDIyLTEzNiA4Ny0xNTAgMjgtNCA3OS00IDQ5LTQ1LTgtMjgtMTMtNTctMjMtODR6IiBzdHlsZT0iZmlsbDojOThlOTE2Ii8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMzM3IDE5NGMtNTgtMy0xMjYgMjgtMTM5IDg5LTEzIDQzIDcgODggNDIgMTE0IDQ0IDQwIDEwOCA2OCAxMjUgMTMxIDExIDQ1LTIwIDEwMi03MSAxMDAtNjAgNC0xMTctMTktMTc0LTM0YTMyOCAzMjggMCAwIDAgMzAzIDE0OWMyOC00IDc5LTQgNTUtNDNMMzQ0IDE5NmMtMS0zLTUtMi03LTJ6IiBzdHlsZT0iZmlsbDojMjRjNDBlIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMzk1IDU2Yy0yNiA0LTk0LTctNzggMzRsNTAgMTg1YzMxLTYgNjQtMzEgOTQtNyA0MCAzNCAzOSA5MyA0MyAxNDIgMyA1OS0yIDEyMCAxNSAxNzggMjEgNDEgNzYgMjAgMTAwLTggNDEtNDQgMzEtMTA5IDIyLTE2My0xMC01OC0yOS0xMjEtNy0xNzkgMTEtMjcgNTgtNDggMTktNzJBMzQ5IDM0OSAwIDAgMCAzOTUgNTZ6IiBzdHlsZT0iZmlsbDojMzg2MGRkIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNNjc0IDE5NGMtNDAgMzItNTQgODYtNDQgMTM1IDggNzQgNDAgMTUwIDEzIDIyMy0xNiAzOC01NyA2NS05OCA2NC00OS0yMC0zNy04My00My0xMjYtNC02OSA2LTE0NS0zMS0yMDctMjUtMzQtNjgtMjAtOTgtMy0yIDQwIDIwIDg0IDI4IDEyNWw4NyAzMjdhMzQ4IDM0OCAwIDAgMCAyNDEtNDM1Yy0xMy0zNi0zMS03Mi01NS0xMDN6IiBzdHlsZT0iZmlsbDojMWRiNmVkIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJtMzEyIDcyIDE3NCA2NTgiIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjI3O3N0cm9rZS1saW5lY2FwOnJvdW5kIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMTEwIDU4OGM2NyAxOSAxMzcgNTAgMjA4IDM0IDUyLTIxIDYxLTk3IDI0LTEzNS00Mi01NS0xMTktNzgtMTQ1LTE0NS0xOC02MCAyMS0xMzEgODQtMTQzIDIwLTYgNDEtOCA2Mi03bTI1IDg3YzMzLTE3IDg1LTM1IDEwNyA4IDMzIDU0IDI2IDEyMSAyOSAxODEgMSA0NS0xIDkyIDIwIDEzMiAyOSAzMiA3OCAzIDEwMS0yMyA0MS01MSAyNi0xMjEgMTUtMTc5LTExLTU3LTMwLTEyNCA3LTE3NiA3LTExIDE2LTIwIDI1LTMwIiBzdHlsZT0iZmlsbDpub25lO3N0cm9rZTojZmZmO3N0cm9rZS13aWR0aDozOSIvPjxwYXRoIHRyYW5zZm9ybT0ibWF0cml4KDEuMTAyNyAwIDAgMS4xMDMzOCAtNDEgLTQyKSIgZD0iTTc0NiA0MDBBMzQ2IDM0NiAwIDEgMSAyNTEgODdjMTM3LTYzIDMxOS0zMiA0MTQgOTAgNTEgNjIgODEgMTQyIDgxIDIyM3oiIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjMzO3N0cm9rZS1saW5lY2FwOnJvdW5kIi8+PC9zdmc+)](https://swung.slack.com/messages/gstools)
```
[![swung-slack-gstools](https://img.shields.io/badge/Swung-Slack-4A154B?style=flat&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MDAiIGhlaWdodD0iODAwIj48cGF0aCB0cmFuc2Zvcm09Im1hdHJpeCgxLjEwMjcgMCAwIDEuMTAzMzggLTQxIC00MikiIGQ9Ik0zMDkgNjdhMzQ2IDM0NiAwIDAgMC0yMDAgNTE4YzY1IDIxIDEzMyA0NyAyMDIgMzcgNTYtMTYgNjYtOTUgMjktMTM0LTQzLTUzLTExNS03OC0xNDQtMTQyLTIzLTYzIDIyLTEzNiA4Ny0xNTAgMjgtNCA3OS00IDQ5LTQ1LTgtMjgtMTMtNTctMjMtODR6IiBzdHlsZT0iZmlsbDojOThlOTE2Ii8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMzM3IDE5NGMtNTgtMy0xMjYgMjgtMTM5IDg5LTEzIDQzIDcgODggNDIgMTE0IDQ0IDQwIDEwOCA2OCAxMjUgMTMxIDExIDQ1LTIwIDEwMi03MSAxMDAtNjAgNC0xMTctMTktMTc0LTM0YTMyOCAzMjggMCAwIDAgMzAzIDE0OWMyOC00IDc5LTQgNTUtNDNMMzQ0IDE5NmMtMS0zLTUtMi03LTJ6IiBzdHlsZT0iZmlsbDojMjRjNDBlIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMzk1IDU2Yy0yNiA0LTk0LTctNzggMzRsNTAgMTg1YzMxLTYgNjQtMzEgOTQtNyA0MCAzNCAzOSA5MyA0MyAxNDIgMyA1OS0yIDEyMCAxNSAxNzggMjEgNDEgNzYgMjAgMTAwLTggNDEtNDQgMzEtMTA5IDIyLTE2My0xMC01OC0yOS0xMjEtNy0xNzkgMTEtMjcgNTgtNDggMTktNzJBMzQ5IDM0OSAwIDAgMCAzOTUgNTZ6IiBzdHlsZT0iZmlsbDojMzg2MGRkIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNNjc0IDE5NGMtNDAgMzItNTQgODYtNDQgMTM1IDggNzQgNDAgMTUwIDEzIDIyMy0xNiAzOC01NyA2NS05OCA2NC00OS0yMC0zNy04My00My0xMjYtNC02OSA2LTE0NS0zMS0yMDctMjUtMzQtNjgtMjAtOTgtMy0yIDQwIDIwIDg0IDI4IDEyNWw4NyAzMjdhMzQ4IDM0OCAwIDAgMCAyNDEtNDM1Yy0xMy0zNi0zMS03Mi01NS0xMDN6IiBzdHlsZT0iZmlsbDojMWRiNmVkIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJtMzEyIDcyIDE3NCA2NTgiIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjI3O3N0cm9rZS1saW5lY2FwOnJvdW5kIi8+PHBhdGggdHJhbnNmb3JtPSJtYXRyaXgoMS4xMDI3IDAgMCAxLjEwMzM4IC00MSAtNDIpIiBkPSJNMTEwIDU4OGM2NyAxOSAxMzcgNTAgMjA4IDM0IDUyLTIxIDYxLTk3IDI0LTEzNS00Mi01NS0xMTktNzgtMTQ1LTE0NS0xOC02MCAyMS0xMzEgODQtMTQzIDIwLTYgNDEtOCA2Mi03bTI1IDg3YzMzLTE3IDg1LTM1IDEwNyA4IDMzIDU0IDI2IDEyMSAyOSAxODEgMSA0NS0xIDkyIDIwIDEzMiAyOSAzMiA3OCAzIDEwMS0yMyA0MS01MSAyNi0xMjEgMTUtMTc5LTExLTU3LTMwLTEyNCA3LTE3NiA3LTExIDE2LTIwIDI1LTMwIiBzdHlsZT0iZmlsbDpub25lO3N0cm9rZTojZmZmO3N0cm9rZS13aWR0aDozOSIvPjxwYXRoIHRyYW5zZm9ybT0ibWF0cml4KDEuMTAyNyAwIDAgMS4xMDMzOCAtNDEgLTQyKSIgZD0iTTc0NiA0MDBBMzQ2IDM0NiAwIDEgMSAyNTEgODdjMTM3LTYzIDMxOS0zMiA0MTQgOTAgNTEgNjIgODEgMTQyIDgxIDIyM3oiIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjMzO3N0cm9rZS1saW5lY2FwOnJvdW5kIi8+PC9zdmc+)](https://swung.slack.com/messages/gstools)

And one last thing: is it possible to align the "Get in touch" section in rtd to the center? :blush:

**Comment by LSchueler** [comment]
> And one last thing: is it possible to align the "Get in touch" section in rtd to the center? blush

I think that is one of the great challenges of humanity! No way! After getting a bit frustrated I realised that everything in sphinx is left aligned, even the badges, so personally I'm fine with it.

**Comment by LSchueler** [comment]
> I found out, that there is a simpler URL to the gstools channel there

That's great! I guess the size of our README has increased by 20% due to the new badges ;-)

**Review by MuellerSeb — APPROVED** [review]

**Comment by MuellerSeb** [comment]
Whoop whoop! :rocket:

**Comment by MuellerSeb** [comment]
> > And one last thing: is it possible to align the "Get in touch" section in rtd to the center? blush
> 
> I think that is one of the great challenges of humanity! No way! After getting a bit frustrated I realised that everything in sphinx is left aligned, even the badges, so personally I'm fine with it.

Ah I remember... rst is a bit frustrating here :confused:

**Pull request merged**
