### PR TITLE
CovModel: Update and Refactoring

### PR DESCRIPTION
**Pull request by MuellerSeb**
This PR updates and refactors the covariance models:
- Fitting routines now support input of directional **empirical variograms** to estimate anisotropy
- add new `rescale` argument and attribute to the `CovModel` class to be able to rescale the `len_scale` (usefull for unit conversion or rescaling `len_scale` to coincide with the `integral_scale` like it's the case with the Gaussian model)
  See: #90, https://github.com/GeoStat-Framework/PyKrige/issues/119
- added new `len_rescaled` attribute to the `CovModel` class, which is the rescaled `len_scale`: `len_rescaled = len_scale / rescale`
- new method `default_rescale` to provide default rescale factor (can be overridden)
- remove `doctest` calls
- docstring updates in CovModel and derived models
- updated all models to use the `cor` routine and make use of the `rescale` argument (See: #90)
- TPL models got a separate base class to not repeat code
- added **new models** (See: #88):
  -  `HyperSpherical`: (Replaces the old `Intersection` model) Derived from the intersection of hyper-spheres in arbitrary dimensions. Coincides with the linear model in 1D, the circular model in 2D and the classical spherical model in 3D
  - `SuperSpherical`: like the HyperSpherical, but the shape parameter derived from dimension can be set by the user. Coincides with the HyperSpherical model by default
  - `JBessel` a hole model valid in all dimensions. The shape parameter controls the dimension it was derived from. For `nu=0.5` this model coincides with the well known `wave` hole model. 
  - `TPLSimple` a simple truncated power law controlled by a shape parameter `nu`. Coincides with the truncated linear model for `nu=1`
- string representation of the `CovModel` class is new using a float precision (`CovModel._prec=3`) to truncate longish output
- dimension validity check: raise a warning, if given model is not valid in the desired dimension (See: #86) 
- more comprehensive testing

### CODE REVIEW

**Comment by MuellerSeb** [comment]
@LSchueler are you willing to take a first look?

**Review by LSchueler — CHANGES_REQUESTED** [review]
This adds a lot of really nice little things to the project!
I think the len_rescale is a very elegant solution to quite some minor problems. - Cool!
But I think you should add some tests for the interactions of the arguments `len_scale`, `integral_scale`, and `len_rescale`.

I fixed some typos directly on this branch... as usual ;-)

**Comment by MuellerSeb** [comment]
@LSchueler thanks :wink:
So I will add a test for `rescale`. Fitting should be tested better as well.

**Comment by MuellerSeb** [comment]
Coverage at 92% now! :tada:

**Pull request merged**
